baseURL:       https://xn--cz8h19c.ml/
languageCode:  de-de
title:         Cheat Sheets
description:   Lernzettel zur Vorbereitung für Klassenarbeiten der Berufsschule bei der Ausbildung zum Mediengestalter Digital und Print.

theme:             [hugo-theme-component-asciidoctor-skin, hugo-theme-seo]
# theme:           [../../../hugoseotheme/hugo-theme-component-asciidoctor-skin, ../../../hugoseotheme/hugo-theme-seo]

params:
  author:          David Wolf
  titleSeparator:  —
  themeColor:      '#FF4500'

  # icons:
  #   favicon:       favicon.svg
  #   touchIcon:     favicon.svg
  #   maskIcon:      mask-icon.svg

  widgetAreas:
    sidebarMobile:
      area:
        symbol:    '☰'
      widgets:
        - widget:  core/toc
        - widget:  core/menusections
        # - widget:  core/menu
    headerTop:
      widgets:
        - widget:  core/breadcrumbs
    # headerSub:
    sidebarLeft:
      widgets:
        - widget:  core/menusections
        # - widget:  core/meta
    sidebarRight:
      widgets:
        - widget:  core/toc
    footer:
      widgets:
        - widget:  share/editongithub
          user:    devidwolf
          repo:    edu
          branch:  master

# menu:
#   main:
#     - name:    WebUntis
#       url:     https://mese.webuntis.com/WebUntis/?school=BK-Technik-Siegen#/basic/timetable
#     - name:    Teams
#       url:     https://teams.microsoft.com
#     - name:    SiWiWissen
#       url:     https://siwiwissen.de
#     - name:    BKT
#       url:     https://berufskolleg-technik.de/
