---
title: Investitionen
date: 2021-09-16
---
:toc:
:icons: font
:!table-caption: font

[cols="25h,75"]
|===
| Prüfungstermin
| Freitag, 17. September 12021 HE
//
// | Inhaltliche Quellen
// a|
// * …
|===

== Begriffe
[cols="40h,60"]
|===
| Investition
| Anschaffung von bspw. Gütern

| Finanzierung
| Kapitalbeschaffung für Investitionen

| Bilanz
| Zusammenhang zwischen Investitionen und Finanzierung

| Aktivseite
a| Vermögenswerte

* Anlagevermögen
* Umlaufvermögen

| Passivseite
a| Vermögensherkunft

* Eigenkapital
* Fremdkapital

| Anlagevermögen
a| Langfristige Vermögensanteile

.Beispiele
* Grundstück
* Maschinen
* Fuhrpark
* Ausstattung

| Umlaufvermögen
a| Kurzfristige Vermögensanteile

.Beispiele
* Warenbestand
* Erzeugnisse
* Kasse
|===

== Arten
Investitionen lassen sich grundlegend in die folgenden vier Arten untergliedern:

[cols="1h,1"]
|===
| Erstinvestition
| Initiale _Gründungsinvestition_

| Erweiterungsinvestition
| Kapazitätserweiterung

| Ersatzinvestition
| Ersatz von z. B. nicht mehr funktionstüchtigen Betriebsmitteln

| Rationalisierungsinvestition
| Austausch/Upgrades zu verbessertem Betriebsmittel
|===

NOTE: Investitionen sind nicht immer einer konkreten Investitionsart zuzuschreiben. Nicht selten handelt es sich bei einer Investition um eine Kombination der aufgeführten Investitionsarten.

== Rechnungen
Zum Vergleich und zur Abwägung der Wirtschaftlichkeit unterschiedlicher Investitionen dienen folgende Berechnungen als Indikator.

=== Kosten- & Gewinnvergleichsrechnungen

.Berechnungs-Tabelle
[cols="25h,5,5,5,10"]
|===
| Jahr | 1 | … | 5 | Gesamt

| Kosten: Fix | … | … | … | …
| Kosten: Variable  | … | … | … | …
| Kosten: Gesamt | … | … | … | …
| Erlös | … | … | … | …
| Gewinn | … | … | … | …
|===

IMPORTANT: Falls die Stückzahl höher ist als die Kapazitätsgrenze gilt: `Stückzahl = Kapazitätsgrenze`

==== Kosten
===== Variable Kosten
----
Variable Kosten = Produzierte Stückzahl * Produktionskosten pro Stück
----

===== Gesamte Kosten
----
Gesamte Kosten = Fixkosten + Variable Kosten
----

==== Erlös
----
Erlös = Verkaufte Stückzahl * Verkaufspreis pro Stück
----

==== Gewinn
----
Gewinn = Erlös - Gesamte Kosten
----

===== Durchschnittlicher Gewinn
----
Durchschnittlicher Gewinn pro Jahr = Summe aller Jahresgewinne / Anzahl der Jahre
----


=== Rentabilitätsrechnung
Anteil von Gewinn an Investitonssumme in %

----
Rentabilität = (Jahresgewinn * 100) / Durchschnittlicher Kapitalbetrag
----

CAUTION: Große Zahl => Gut (weil dann Gewinn deckt Investition zu gegebenen Anteil)

==== Durchschnittlicher Kapitalbetrag
----
Durchschnittlicher Kapitalbetrag = Investitonssumme / 2
----


=== Amortisationsrechnung
Die Jahre bis abbezahlt (Kapitalrückflusszeit)

----
Kapitalrückflusszeit = Investitionsbetrag / (Jahresgewinn + Jahresabschreibung)
----

CAUTION: Kleine Zahl => Gut (weil dann schnell abbezahlt)

== Multiple-Choice
IMPORTANT: Immer *nur eine einzige* Lösung ist richtig

=== Arbeitsverhältnis
* bei Arbeitsunfähigkeit
** am nächsten Arbeitstag ärztliche Bescheinigung
** 6 Wochen Anspruch auf Gehalt
** danach Krankengeld (ca. 65% des Gehalts)
* Lohn
** Zeitlohn nach Zeit
** Akkordlohn nach Leistung
* Arbeitszeit
** 8 Stunden generelles, regelmäßiges Maximum
** 10 Stunden, wenn innerhalb 6 Monate 8
